spring.application.name=journal

spring.data.mongodb.uri=mongodb+srv://rakeshsarkar20066_db_user:JournalApp@journalapp.fpxd9ub.mongodb.net/journaldb?retryWrites=true&w=majority
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
spring.data.mongodb.auto-index-creation=true